/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CursosAdmin;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jancarloticun
 */
public class Login extends javax.swing.JFrame {

    public ArrayList<Alumno> alumnos;
    public ArrayList<Profesor> profesores;
    public ArrayList<Curso> cursos;
    /**
     * Creates new form Login
     */
    public Login(ArrayList<Alumno> alumnos, ArrayList<Profesor> profesores, ArrayList<Curso> cursos ) {
        initComponents();
        this.alumnos = alumnos;
        this.profesores = profesores;
        this.cursos = cursos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUsuarioNombre = new javax.swing.JTextField();
        jUsuarioPassword = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlogin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlogin.setText("Login");

        jLabel1.setText("Escriba su usuario");

        jLabel2.setText("Escriba su password");

        jUsuarioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuarioNombreActionPerformed(evt);
            }
        });

        jUsuarioPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuarioPasswordActionPerformed(evt);
            }
        });

        jButtonIniciar.setText("Iniciar Sesion");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jUsuarioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsuarioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsuarioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuarioNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsuarioNombreActionPerformed

    private void jUsuarioPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuarioPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsuarioPasswordActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        String usuario = jUsuarioNombre.getText();
        String password = jUsuarioPassword.getText();
        
        if("ADMIN".equals(usuario)&&"PROGRA1".equals(password)){
            AdminPanel admin = new AdminPanel(this.alumnos, profesores,cursos);
            admin.setVisible(true);
        } else {
            Profesor loginProf = null;
            for(int i = 0; i<profesores.size();i++){
               Profesor p = profesores.get(i);               
               if(p.password.equals(password) && p.usuario == Integer.parseInt(usuario)) {
                   loginProf = p;
                   ProfesorPanel pr = new ProfesorPanel(p);
                   pr.setVisible(true);
                   break;
               }
            }
            Alumno loginAlm = null;          
            for(int e = 0; e <alumnos.size(); e++){
                   Alumno a = alumnos.get(e);
                   if(a.password.equals(password) &&  a.carnet == Integer.parseInt(usuario)){
                       loginAlm = a;
                       AlumnoPanel al = new AlumnoPanel(a, this.cursos);
                       al.setVisible(true);
                       break;
                   }
            }
            if(loginProf==null && loginAlm==null){
                JOptionPane.showMessageDialog(this, "Usuario invalido");
            }
        }  
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jUsuarioNombre;
    private javax.swing.JTextField jUsuarioPassword;
    private javax.swing.JLabel jlogin;
    // End of variables declaration//GEN-END:variables
}
